### ISSUE TITLE
[boxplots] Minor ticks

### ISSUE THREAD

**Issue by FMassin** [SeismicSource/sourcespec#11]
Hello

What a great tool @claudiodsf !!! Thanks you so much for sharing this! Just a little idea, add something like
```
ax.minorticks_on()
```
to https://github.com/SeismicSource/sourcespec/blob/7dbe485b6b3375e938d1a87b97393d1aaf8456da/sourcespec/ssp_plot_params_stats.py#L89

Cheers

Fred

**Comment by claudiodsf** [comment]
Merci Fred !

Done in 92b3e74!

Don't hesitate to propose PRs :😉

**Comment by FMassin** [comment]
Awesome! Thanks a lot!
![ineter2022rlru boxplot](https://user-images.githubusercontent.com/10435362/189891234-fd1d3ff7-8588-435b-b151-2ce6d050cabb.png)

**Comment by claudiodsf** [comment]
A bit low that Mw estimate... 

https://earthquake.usgs.gov/earthquakes/eventpage/us7000i5kj/executive
