### ISSUE TITLE
Problem in _smooth_spectrum function

### ISSUE THREAD

**Issue by krisvanneste** [SeismicSource/sourcespec#2]
I think there is a problem in the _smooth_spectrum function. When the spectrum is converted from linear space to log space, the spectrum is first decimated to 50 points (the default number of values generated by np.logspace) before the actual smoothing is applied.

To avoid loosing nformation, it would be much better to generate the freq_log sequence with the smallest log_df spacing in the linear series, as follows:
`log_df = np.diff(np.log10(freq[-2:]))[0]`
`freq_log = 10**(np.arange(np.log10(freq[0]), np.log10(freq[-1]) + log_df, log_df))`

When you do that, however, the 'npts' argument doesn't make much sense anymore. It would be better to define the amount of smoothing in terms of bandwidth in log space. The number of points can then be computed from the bandwidth as follows:
`npts = max(1, int(round(bandwidth / log_df)))`

https://github.com/SeismicSource/sourcespec/blob/3ad78e9b3e00c64676fefb676cfec7e5f259dcc1/sourcespec/ssp_build_spectra.py#L216

**Comment by claudiodsf** [comment]
Hi Kris and thanks for the feedback!

What you propose is very interesting.

I'm going to create a branch so that we can test this idea.

**Comment by krisvanneste** [comment]
Claudio,
Thanks for looking into this!

Kris

**Comment by krisvanneste** [comment]
Claudio,

`log_bandwidth` should be an argument of the _smooth_spectrum function (replacing `npts`). I use a default value of 0.05, which seems to give good results, but it should be configurable by the end user.

Kris

**Comment by krisvanneste** [comment]
Claudio,

Thanks for updating your code. I can't run sourcespec to evaluate the impact on the magnitude estimation right now, but I will try to evaluate the spectral smoothing by tomorrow, if that's OK.

Kris

**Comment by claudiodsf** [comment]
No worry! Take your time!

**Comment by claudiodsf** [comment]
Just pushed a new commit https://github.com/SeismicSource/sourcespec/commit/16949b12a0887adce532fba37df5c8ea204fd8d3 

Here I resample the smoothed log-spectrum using a sampling rate that is 1/5 of the smooth window size.

In my tests, it is a sufficient number of points to correctly represent the smoothed spectrum.

Let me know what do you think.

**Comment by krisvanneste** [comment]
Claudio,

I compared your new smoothing function with mine and with your previous one in the attached plot.

With the same bandwidth (`smooth_width_decades`), the result of the new smoothing function is very close to mine (labeled "robspy" in the plot). With the default value of 0.2, it is close to your original function. Anyway, the new function can be configured much better than the original one, which smoothed a great deal more than you would expect with a smoothing window (`npts`) of only 5 points.

The only potential problem I see is that in your spec object, the linear spectrum (spec.freq, spec.data) has a different resolution compared to the logarithmic spectrum (spec.freq_log, spd.data_log). I hope this doesn't cause any problems later on in the process.

Kris
![spectral_smoothing_comparison](https://user-images.githubusercontent.com/2128835/156343947-8fde0a37-f37b-446f-97a1-43120f6919cd.PNG)

**Comment by claudiodsf** [comment]
Hi Kris and thanks for this test!

It looks like I prefer smoothing more than you 😉. So it's good to have a parameter for that!

The linear spectrum is not used anymore, except for plotting. But I think I'll replace `spec.data` with `spec.data_log` also for plotting, so that one can visually judge the effect of the downsampling.

I'll do this latest modification later today and then merge the `smooth_spectrum` branch.

Thanks again!

**Comment by krisvanneste** [comment]
Claudio,

OK, thanks for addressing this!
And yes, maybe I need to smooth a little more...

Kris
