### ISSUE TITLE
Noise windows are shifted

### ISSUE THREAD

**Issue by claudiodsf** [SeismicSource/sourcespec#21]
Hi @krisvanneste,

the changes introduced with #18 are causing a small but significant problem in my case: the noise window is shifted and a trace is rejected.

This is due to [this line](https://github.com/SeismicSource/sourcespec/blob/dc4af750bcdae4a83213d56945d129f04beb51d0/sourcespec/ssp_process_traces.py#L311):

```python
t1 = max(trace.stats.starttime, p_arrival_time - config.noise_pre_time)
``` 

which used to be:

```python
t1 = p_arrival_time - config.noise_pre_time
```

Attached two figures showing the old and the new behaviour.

Could you explain why this change is important for you use case? Any idea for a workaround?

![fr2022kgxxrg traces](https://user-images.githubusercontent.com/1390993/210846402-4b00747f-1391-4d14-a426-037e18de33ec.svg)

![fr2022kgxxrg traces-2](https://user-images.githubusercontent.com/1390993/210846487-cabadb70-b92f-44d2-94d9-18bad80b71ad.svg)

**Comment by krisvanneste** [comment]
Hi Claudio,

I made this change to make sure that the start of the noise window is not before the start of the trace. Without that constraint, the obspy trim operation (in the _cut_signal_noise function) just fills the missing part with zeros. So, the noise window was never considered too short, even if it was absent.

I'm not sure why the noise window is shifted in your case, but it is possible that a trace that was not rejected before is now rejected. The filling in of the missing part with zeros (old behavior) would result in a lower SNR (which is not real).

Could you check if the amount of time before the P arrival with respect to your noise_pre_time for the rejected record?

**Comment by krisvanneste** [comment]
I also think the plot may be misleading. In my case, in the previous behavior, it shows noise windows (flat lines), where there is no data in my trace. Have a look at the image: stations MASA, STWA and CLHA are late triggered (part of the P window is even missing in STWA), but yet a noise window is drawn.

![1306 traces 00](https://user-images.githubusercontent.com/2128835/210969207-b4de7268-644b-40b4-bddb-723b19c8dce4.png)

**Comment by claudiodsf** [comment]
Ok, I think I should change the way traces are plotted (or are trimmed?) to avoid this impression of having signal, when it is not there.

Ideally, your plot for, e.g., BE.CLHA should not show any signal before a few seconds before S arrival.

**Comment by claudiodsf** [comment]
I'll prepare a pull request and I will ask you to test it, if you don't mind.

**Comment by krisvanneste** [comment]
OK, could you also check if the noise windows are drawn for each trace separately or if it the same box is used for each trace?

**Comment by claudiodsf** [comment]
You mean each of the three components, for a given station?

**Comment by krisvanneste** [comment]
Yes.

**Comment by claudiodsf** [comment]
Probably it is the same box. I'll try and fix that.

**Comment by claudiodsf** [comment]
Looks like the fix is quite easy: could you please comment out line 380 in `ssp_plot_traces.py`:

```python
_trim_traces(config, st_sel)
```
And see what happens in your case?

**Comment by krisvanneste** [comment]
It's a big difference! Missing data are no longer plotted, but the traces are much longer, making it more difficult to see the selected windows.

![1306 traces 00](https://user-images.githubusercontent.com/2128835/210977424-a8259a8d-d816-41b8-8c27-f4ec1e407daf.png)

**Comment by claudiodsf** [comment]
Ok, can you try changing line 311:

```python
trace.trim(starttime=t1, endtime=t2, pad=True, fill_value=0)
```

with
```python
trace.trim(starttime=t1, endtime=t2)
```

Of course, remove the comment from line 380 😉

**Comment by claudiodsf** [comment]
The idea in `_trim_traces()` is to plot a time window which is three times the length of the analysis window.

**Comment by claudiodsf** [comment]
Great! Looking at the code, noise windows should be plotted separately for each component. Do you have an example where they're not there same, to check that?

**Comment by krisvanneste** [comment]
Not straightaway. I trimmed all records in my archive to the same start time.
I thought maybe in your example, the station FR.PLOF.00 could have different start times for the different components?
If not, I will see if I can test it by cutting 1 component before sending it to sourcespec.

**Comment by claudiodsf** [comment]
The only problem I see is that noise and signal windows are plotted as vertical spans, so they always cover the full plot in vertical.

This can be improved by plotting rectangular patches of 1/3rd of the plot height... looking into that.

**Comment by krisvanneste** [comment]
I was going to say that it also depends on the selected wave_type (e.g. for P-wave only Z component is used), but I think in ssp_process_traces all components are processed separately. So, the noise windows could still be different.

**Comment by claudiodsf** [comment]
Ok, I modified the code to plot the patch separately.

I made a test randomising the noise and signal windows, just to see the effect: is that fine for you?

![fr2022kgxxrg traces](https://user-images.githubusercontent.com/1390993/211003110-c8437486-7732-472a-b5be-e0e2a37db118.svg)

Note: the code is not yet pushed to the repository.

**Comment by krisvanneste** [comment]
That looks fine!

**Comment by claudiodsf** [comment]
Sorry, I had to force-push https://github.com/SeismicSource/sourcespec/commit/92ddf7a1f3a6e8eb1d8e6e0388cdca195d2e757c
