### ISSUE TITLE
Handling of SV wave in _compute_h function

### ISSUE THREAD

**Issue by krisvanneste** [SeismicSource/sourcespec#3]
Shouldn't this line be:
`if wave_type == 'SV' and channel[-1] not in ('R', 'Z'):`
or perhaps
`if wave_type == 'SV' and channel[-1] == 'T':`

If I understand correctly, R components are currently skipped when the SV wave is selected, and instead T and Z components are combined.

Kind regards,
Kris Vanneste

https://github.com/SeismicSource/sourcespec/blob/3ad78e9b3e00c64676fefb676cfec7e5f259dcc1/sourcespec/ssp_build_spectra.py#L106

**Comment by claudiodsf** [comment]
That's right!

Fixed, Thanks!
