### ISSUE TITLE
Absolute file paths on linux

### ISSUE THREAD

**Issue by krisvanneste** [SeismicSource/sourcespec#40]
When running sourcespec on our linux server, I experience a problem with the path to the output folder. If I specify an absolute path (e.g. /mnt/geoserver/Belshake/sourcespec), the output is written to a folder relative to the working directory (e.g. /home/kris/mnt/geoserver/Belshake/sourcespec). On Windows, this does not happen.

The problem seems to be situated in the move_outdir function in ssp_setup.py:
```
    path = os.path.normpath(config.options.outdir).split(os.sep)
    dst = os.path.join(*path[:-1], str(evid))
```
Leading slashes are removed in `dst`. Is this intentional? I didn't change anything, but solved it by running everything from the root folder...

**Comment by claudiodsf** [comment]
Thanks for reporting this!

It should be now fixed in the `main` branch.

Could you please double-check on Windows and Linux?

**Comment by krisvanneste** [comment]
Works both on Windows and Linux!

**Comment by krisvanneste** [comment]
Sorry, no. I will try that too.

**Comment by krisvanneste** [comment]
Relative paths also work as expected on both platforms.

**Comment by claudiodsf** [comment]
Super! Closing!
