### ISSUE TITLE
Duplicate SQL records

### ISSUE THREAD

**Issue by krisvanneste** [SeismicSource/sourcespec#41]
Claudio,

I'm experiencing a strange problem with SQLite output.
I need to run sourcespec again for a number of events. As I am using the same run_id, I expected the previous results to be overwritten, but instead I now have duplicate entries, as you can see in the screenshot:
![image](https://github.com/SeismicSource/sourcespec/assets/2128835/05ed7b3c-56ec-47dd-872c-96319a80b642)

However, the code to delete existing records for a given event_id, (station) and run_id is still there, and it should generate an error message if it fails, and exit, but none of that has happened.

Do you have an idea how this is possible? I did manually set the user_version of the database, added the new 'Er_is_outlier' column, and reordered the columns, but I don't understand why this would affect deletion of records, but not insertion...

**Comment by krisvanneste** [comment]
I failed to notice there has been a change in ssp_sqlite_output.py. I reverted to the commit before, and it seems to work again now. It is possible the problem occurs because my database does not have the primary keys, as it was created before this change.

**Comment by krisvanneste** [comment]
I used the `update_db_file` function to update my database file, and it worked. The Stations and Events tables have primary keys now.

**Comment by claudiodsf** [comment]
Great! Guess I can close this issue, then.

**Comment by krisvanneste** [comment]
Yes!
