### ISSUE TITLE
Fixed corner case in computing spectral_snratio_fmin and spectral_snratio_fmax

### ISSUE THREAD

**Issue by claudiodsf** [SeismicSource/sourcespec#42]
Hi @krisvanneste,

could you please check commit b746bd8a1c82a4779e2413c2826139d4d2deea8e ?

I needed to rewrite the logic of your code, to fix a corner case, when `spectral_win_length` is defined in the config file.

Please also note that you might need to adjust your config structure, because of commit 792444338d90f767be2e4f067496f6946d98ea3c.

Thanks!

**Comment by krisvanneste** [comment]
Claudio,
I will look at it when I can. I'm leaving to Berlin for the IUGG meeting in 2 days, but I think I will find some time in between sessions...

**Comment by krisvanneste** [comment]
Claudio, I tested your fix and obtain the same results as before. So this issue can be closed.

**Comment by claudiodsf** [comment]
Great! Closing
