### ISSUE TITLE
Problem with vp_source, vs_source

### ISSUE THREAD

**Issue by krisvanneste** [SeismicSource/sourcespec#47]
@claudiodsf ,

Before working on the variable window length issue, I need to update my code to run sourcespec. I managed to catch up with most of your recent changes, but I run into a problem when I try to set the VP and VS of the event hypocenter:

```
  File "E:\Home\_kris\Python\seismo\robspy\sourcespec.py", line 113, in prepare_for_sourcespec
    ssp_read_traces._hypo_vel(event.hypocenter, config)

  File "C:\Users\kris\Documents\Python\cloned_repos\sourcespec\sourcespec\ssp_read_traces.py", line 261, in _hypo_vel
    vp_string = medium_properties.to_string('vp_source', hypo.vp)

  File "C:\Users\kris\Documents\Python\cloned_repos\sourcespec\sourcespec\ssp_util.py", line 247, in to_string
    if value.is_integer():

AttributeError: 'numpy.float32' object has no attribute 'is_integer'
```

I don't know how to solve this. The `vp_source` and `vs_source` properties of the `config` object passed to `_hypo_vel` are lists of floats, but apparently they should be objects having an `is_integer` method. However, I couldn't find any class definition with an `is_integer` method in sourcespec. When I comment out the offending lines in the `to_string` method of `MediumProperties`, everything seems to work. However, I notice that there are at least 2 other places where this `is_integer` method is called in sourcespec, so I'm probably doing something wrong. I hope you can tell me.

Kris

**Comment by krisvanneste** [comment]
Claudio,

Indeed, it is a numpy float.

**Comment by claudiodsf** [comment]
Hopefully fixed by 165e20ff4c7f8547e32ad30fc9ecdd1bf84135c2.

Can you check?

**Comment by claudiodsf** [comment]
You probably have an old NumPy version, since `is_integer()` was added to NumPy in version 1.22.0: https://numpy.org/doc/stable/release/1.22.0-notes.html

**Comment by krisvanneste** [comment]
Claudio,
The fix is working!
Indeed, an older numpy version (although it is composed of the same digits: 1.20.2).
I was not aware of this `is_integer` method for python and numpy floats.
Kris

**Comment by claudiodsf** [comment]
Just made commit 6e8df95da56818b82107e42c0d5c6112c0302b99 to fix this everywhere.

It's indeed just a (hackish?) solution to pretty print pure integers 😉

**Comment by krisvanneste** [comment]
Thanks!
