### ISSUE TITLE
Ambiguity between hypocentral and station velocity when not using NLL grids

### ISSUE THREAD

**Issue by krisvanneste** [SeismicSource/sourcespec#5]
I noticed that the `_displacement_to_moment` function in `ssp_build_spectra` calls `ssp_util.get_vel` to obtain `vs_station`.
However, when there is no NLL grid, `ssp_util.get_vel` just returns `config.vs`, which according to `sourcespec.conf` is the S-wave velocity close to the source. The` _hypo_vel` function in `ssp_read_traces` also calls `ssp_util.get_vel` and stores the same value in `config.hypo.vs`. So, when not using NLL grids, hypocentral and station velocities end up with the same value.

Would it be possible to define hypocentral and station velocities (P and S) separately in sourcespec.conf?

**Comment by krisvanneste** [comment]
Claudio,

Yes, separate v[p/s]_source and v[p/s]_stations configuration parameters would be great. However, it means that older sourcespec.conf files will not work anymore... Another difficulty will be to update the ssp_util.get_vel function, which should return either v_source or v_stations. I suppose this can be done based on the depth value, because the hypocentral depth is known in config.hypo.depth.

Concerning vp_tt and vs_tt: Besides travel time calculation (in ssp_wave_arrival.add_arrivals_to_trace), these parameters are also used to compute the quality factor (in ssp_inversion._spec_inversion) and to set bounds on t_star (in ssp_data_types._Qo_to_t_star). In both cases, hypocentral velocities are used if they are not defined. Perhaps using the average of v_source and v_stations would be slightly better in that case.

Kris

**Comment by claudiodsf** [comment]
> Yes, separate v[p/s]_source and v[p/s]_stations configuration parameters would be great. However, it means that older sourcespec.conf files will not work anymore... 

It is not a goal of SourceSpec to keep backwards compatibility of `sourcespec.conf`: the config file can be updated via `source_spec -U <config_file>`, so this is a non-issue 😉 

> Another difficulty will be to update the ssp_util.get_vel function, which should return either v_source or v_stations. I suppose this can be done based on the depth value, because the hypocentral depth is known in config.hypo.depth.

Even better, I would compute, for the given arbitrary point, distance from station and distance from hypo and use the closest velocity. 

> Concerning vp_tt and vs_tt: Besides travel time calculation (in ssp_wave_arrival.add_arrivals_to_trace), these parameters are also used to compute the quality factor (in ssp_inversion._spec_inversion) and to set bounds on t_star (in ssp_data_types._Qo_to_t_star). In both cases, hypocentral velocities are used if they are not defined. Perhaps using the average of v_source and v_stations would be slightly better in that case.

Good catch!


I will make these modifications and report back here 😉

**Comment by krisvanneste** [comment]
Claudio,

OK, these modifications will probably impact the P_wave_type branch that I am preparing, but we will see.

Kris

**Comment by claudiodsf** [comment]
Don't worry, I will rebase before merging.

**Comment by claudiodsf** [comment]
I have just pushed 4 commits to the master branch which should fix this issue.

- concerning the automatic choice of `vp[vs]_source` with respect to `vp[vs]_stations`, I finally implemented your suggestion which was much easier 😉 
- concerning quality factor computation, I now store travel time in trace and spectral objects and use it for the computation

Could you please check if the code works on your side?

P.S. For the moment, I assume the S-wave travel time. In your `P_wave_type` branch you should add a check...

**Comment by krisvanneste** [comment]
I just prepared the two other pull requests. I'm pretty sure the P_wave_type branch will conflict with your new modifications.
Unfortunately, I will not be able to test your changes and resolve the conflicts immediately, due to a meeting tomorrow.

**Comment by claudiodsf** [comment]
No problem: I also will be offline tomorrow (July 14 🇫🇷) and on Friday (bridge 😉).

**Comment by krisvanneste** [comment]
OK, enjoy your national holiday! Next week, it's our turn (July 21 + bridge as well)!

**Comment by claudiodsf** [comment]
> This confirms that your changes are working for me, but I must confess that I run sourcespec slightly differently than intended: I skip the parse_args, configure and read_traces stages, so if there would be problem there, I would not catch it.

Great! I will close this issue as resolved, then. 

I'me very curious to know how you run SourceSpec (directly from Python?). Could you please share a use case?

**Comment by claudiodsf** [comment]
Interesting!

Maybe one day (no rush!) we could include this Python interface into the code.

**Comment by krisvanneste** [comment]
> Maybe one day (no rush!) we could include this Python interface into the code.

I think it would be possible to include some of it in SourceSpec directly. A first idea would be to add a function in source_spec.py that takes 'st' and 'config' arguments, and contains the code from the main section (minus parse_args, read_traces and ssp_exit) and perhaps returns proc_st, spec_st, specnoise_st, weight_st and sourcepar. This function could be called from the main section and perhaps it is also possible to add a higher-level function building further on that...

From my side, I will not be able to work on that before I return from holidays (mid-August).

**Comment by claudiodsf** [comment]
Sure, no need to rush on that.

(Working on "P_wave" PR right now ;-)
